from typing import Dict
from models import GameInfo

#Idea di renderlo un dizionario di dizionari con regole, numero minimo e massimo di giocatori, numero e tipo di mazzi necessari ecc.

#gin rummy, canasta

#giochi a vite? (trentuno)
#giochi a squadre (scopa, burraco, tressette, briscola ecc.)
#altri tipi?

#Cacace -> King
#Peppa -> Hearts (ma va bene anche Peppa)
#Machiavelli finisce subito senza punti?
#non puoi scartare una carta che potevi attaccare


games_info: Dict[str, GameInfo] = {
    "cacace" : GameInfo (
        regole = "Il Cacace è un gioco di carte francesi per 4 giocatori dalla durata orientativa di un'ora. È composto da 10 turni di gioco con regole diverse, in ognuno dei quali vengono distribuite ai giocatori tutte le carte di un mazzo, ad eccezione dei jolly. Butta la prima carta a terra il giocatore che segue il mazziere. Il principio base è quello di giocare una carta a terra e gli altri giocatori dovranno rispondere in ordine con una carta dello stesso seme. Prende il giocatore con la carta più alta e sarà quello che giocherà la prossima carta a terra. La carta più bassa è il 2, dopo il 10 vengono il jack, la donna e il re. L'asso è la carta più alta.  È possibile rispondere con un seme diverso da quello giocato solo nel caso in cui si fosse piombo, ovvero non si avesse in mano nessuna carta di quel seme. L'unica eccezione a questo principio base è quello nei 4 turni di briscola. In questi turni, se giocata una briscola a terra, prende sempre la briscola più alta, seguendo le altre regole già spiegate. Vince il giocatore con più punti. Nel primo turno ogni presa vale -1. . Nel secondo turno ogni jack  e re preso vale -2. Nel terzo turno ogni Rregina presa vale -4. Nel quarto turno oil re di cuori vale -8. Nel quinto turno dichiaraa il seme di briscola il giocatore successivo a quello che dà carte e ogni presa vale +1 e così a seguire per il sesto, settimo e ottavo turno. Nel nono turno ogni carta di picche vale -1. Nel decimo turno ogni presa vale +1.",
        min_giocatori = 4,
        max_giocatori = 4,
    ),
    "peppa" : GameInfo(
        regole = "La Peppa è un gioco di carte francesi per 4 giocatori dalla durata orientativa di un'ora. È un gioco composto da un numero variabile di turni, in ognuno dei quali vengono distribuite ai giocatori tutte le carte di un mazzo, ad eccezione dei jolly. Prima di incominciare ciascun turno, i giocatori si scambiano tra di loro 3 carte seguendo quest'ordine ciclico: scambio col giocatore a sinistra, poi alla destra, poi di fronte, ovvero in diagonale, e infine un turno senza scambi. Fatto ciò, il giocatore che ha in mano il 2 di fiori lo butta a terra e si inizia a giocare.  Il principio base è quello di giocare una carta a terra e gli altri giocatori dovranno rispondere in ordine con una carta dello stesso seme. Prende il giocatore con la carta più alta e sarà quello che giocherà la prossima carta a terra. La carta più bassa è il 2, dopo il 10 vengono il jack, la donna e il re. L'asso è la carta più alta.  È possibile rispondere con un seme diverso da quello giocato solo nel caso in cui si fosse piombo, ovvero non si avesse in mano nessuna carta di quel seme. Non si può giocare a terra una carta di cuori fino a quando non è stato rotto il seme, ovvero non è già stata nello stesso turno buttata una carta di cuori a terra quando un giocatore è piombo. Ogni carta di cuori vale -1, mentre la Q di picche, la cosiddetta peppa, vale -13. Se però un unico giocatore prende sia la peppa che tutte le carte di cuori fa cappotto, ovvero non totalizza -26 punti, ma sono tutti gli altri giocatori a prendere quei punti. La partita finisce quando un giocatore raggiunge -100 punti e vince chi ha totalizzato meno punti negativi",
        min_giocatori = 4,
        max_giocatori = 4,
    ),
    "ramino" : GameInfo(
        regole = "Il Ramino è un gioco di carte francesi da 2 a 6 giocatori. Si utilizzano due mazzi di carte francesi con jolly. Il mazziere distribuisce 10 carte a ciascun giocatore e pone una carta scoperta sul tavolo a formare il mazzo degli scarti. Le restanti carte costituiscono il mazzo di pesca. Il primo giocatore pesca una carta dal mazzo oppure prende la carta scartata dal giocatore precedente. Nel proprio turno può formare combinazioni come scale, ovvero tre o più carte in sequenza dello stesso seme, o tris/quaterne, vale a dire tre o quattro carte dello stesso valore con semi diversi. Durante il gioco è possibile attaccare carte a combinazioni già formate. L’asso può essere utilizzato sia prima del 2 che dopo il Re nelle scale, mentre il jolly può sostituire qualsiasi carta. Alla fine del turno il giocatore scarta una carta e passa la mano al successivo. Quando un giocatore esaurisce le carte termina la smazzata e gli altri conteggiano i punti negativi in base alle carte rimaste in mano. Le carte numeriche valgono il loro valore, le figure 10 punti, l’asso 11 e il jolly 25. Se un giocatore chiude in un solo turno senza aver mai calato o attaccato carte, realizza “ramino” e i punti negativi degli altri giocatori vengono raddoppiati. La partita termina quando un giocatore raggiunge -101 punti. Vince chi ha il punteggio negativo più basso.",
        min_giocatori = 2,
        max_giocatori = 6,
    ),
    "scala quaranta" : GameInfo(
        regole = "Scala quaranta è un gioco di carte francesi da 2 a 6 giocatori. Si utilizzano due mazzi di carte francesi con jolly. Il mazziere distribuisce 13 carte a ciascun giocatore e pone una carta scoperta sul tavolo a formare il mazzo degli scarti. Le restanti carte costituiscono il mazzo di pesca. Il primo giocatore pesca una carta dal mazzo oppure prende l'ultima carta scartata a terra. Nel proprio turno può formare combinazioni come scale, ovvero tre o più carte in sequenza dello stesso seme, o tris e quaterne, vale a dire tre o quattro carte dello stesso valore con semi diversi. L’asso può essere utilizzato sia prima del 2 che dopo il Re nelle scale, mentre il jolly può sostituire qualsiasi carta. Durante il gioco è possibile attaccare carte a combinazioni già formate. Tuttavia, il giocatore, prima di poter calare carte a terra, necessita di un'apertura di almeno 40 punti (ti spiegherò i punti associati alle carte a breve). Inoltre, un giocatore può pescare carte dagli scarti solo se ha già effettuato l'apertura o la farà dopo aver pescato. Un giocatore che ha effettuato apertura, può inoltre sostituire il jolly a terra con la carta corrispondente, lo prende e lo deve usare per calare una combinazione o attaccarlo ad una già esistente.  Alla fine del turno il giocatore scarta una carta e passa la mano al successivo. Quando un giocatore rimane termina le carte in mano effettuando lo scarto, termina il turno di gioco e gli altri giocatori conteggiano i punti negativi in base alle carte rimaste in mano. Alle carte numeriche corrisponde un numero di punti pari al loro valore, alle figure 10 punti, all’asso 11 e al jolly 25.  La partita termina quando un giocatore raggiunge -101 punti. Vince chi ha il punteggio negativo più basso.",
        min_giocatori = 2,
        max_giocatori = 6,
    ),
    "machiavelli" : GameInfo(
        regole = "Il Machiavelli è un gioco di carte francesi da 2 a 6 giocatori. Si utilizzano due mazzi di carte francesi con jolly. Il mazziere distribuisce 13 carte a ciascun giocatore. Le restanti carte costituiscono il mazzo di pesca. Il primo giocatore pesca una carta dal mazzo. Nel proprio turno può formare combinazioni come scale, ovvero tre o più carte in sequenza dello stesso seme, o tris e quaterne, vale a dire tre o quattro carte dello stesso valore con semi diversi. L’asso può essere utilizzato sia prima del 2 che dopo il Re nelle scale, mentre il jolly può sostituire qualsiasi carta. Durante il gioco è possibile attaccare carte a combinazioni già formate. Oltre a ciò, è possibile anche modificare le combinazioni già presenti nel tavolo a proprio piacimento: l'importante è che al termine della propria mano di gioco ci siano a terra tutte combinazioni valide. Alla fine del turno il giocatore passa la mano al giocatore successivo. Quando un giocatore esaurisce le carte termina per tutti il turno di gioco e gli altri conteggiano i punti negativi in base alle carte rimaste in mano. Le carte numeriche valgono il loro valore, le figure 10 punti, l’asso 11 e il jolly 25. La partita termina quando un giocatore raggiunge -101 punti. Vince chi ha il punteggio negativo più basso.",
        min_giocatori = 2,
        max_giocatori = 6,
    ),
    "gin rummy" : GameInfo(
        regole = "Il Gin rummy è un gioco di carte francesi per 2 giocatori. Si utilizza un solo mazzo di carte francesi senza jolly. Il mazziere distribuisce 10 carte a ciascun giocatore e pone una carta scoperta sul tavolo a formare il mazzo degli scarti. Le restanti carte costituiscono il mazzo di pesca. Prima di inziare il gioco vero e proprio, il giocatore successivo al mazziere può decidere di prendere la carta da terra e in tal caso inizia il mazziere. Se non lo fa, lo può fare il mazziere e parte l'altro giocatore. Il primo giocatore pesca una carta dal mazzo oppure prende la carta scartata dal giocatore precedente. L'obiettivo è formare nella propria mano combinazioni come scale, ovvero tre o più carte in sequenza dello stesso seme, o tris e quaterne, vale a dire tre o quattro carte dello stesso valore con semi diversi. L’asso può essere utilizzato solo prima del 2 e non dopo il Re nelle scale. Alla fine del turno il giocatore scarta una carta e passa la mano al successivo. Quando un giocatore decide di bussare, scarta la carta a faccia in giù e cala tutte le combinazioni che ha in mano. L'altro giocatore fa lo stesso, ma ha il vantaggio di poter attaccare le proprie carte isolate a quelle già calate dall'avversario. Quest'ultima operazione è vietata se il giocatore che ha bussato ha realizzato gin rummy, ovvero è rimasto senza carte in mano. Le carte numeriche valgono il loro valore, quindi l’asso 1, mentre le figure valgono 10. Ciascun giocatore conta il punteggio relativo alle carte che gli sono rimaste in mano. Il giocatore che ha meno punti in mano, guadagna punti. Questi sono pari alla differenza tra i punti in mano all'altro giocatore e quelli nella propria mano. Vince il giocatore che per primo raggiunge i 100 punti. ",
        min_giocatori = 2,
        max_giocatori = 2,
    )
}
